import os
from typing import TypedDict, Annotated
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import StateGraph, END
from langgraph.graph.message import add_messages

# 1. Open the hidden vault
load_dotenv()

# 2. Define the State (The shared memory for the interview)
class InterviewState(TypedDict):
    problem_context: str            
    messages: Annotated[list, add_messages] 
    current_phase: str              

# 3. Wake up the Groq Brain
llm = ChatGroq(
    api_key=os.getenv("GROQ_API_KEY"),
    model="llama-3.1-8b-instant" 
)

# 4. Define Agent 1: The Algorithm Expert
def algorithm_agent(state: InterviewState):
    system_prompt = SystemMessage(
        content=(
            "You are a Senior Software Engineer interviewing a candidate. "
            "Your focus is purely on algorithm design and data structures. "
            f"Here is the problem they are solving: {state['problem_context']}\n"
            "RULE 1: Ask them how they would approach it conceptually first. Do not ask for code immediately. "
            "RULE 2: Never give the answer. Guide them with Socratic questions."
        )
    )
    
    # Combine the instructions with the user's chat history
    conversation = [system_prompt] + state["messages"]
    response = llm.invoke(conversation)
    
    return {"messages": [response]}

# 5. Build the LangGraph Workflow
def build_interview_graph():
    workflow = StateGraph(InterviewState)
    workflow.add_node("algo_expert", algorithm_agent)
    workflow.set_entry_point("algo_expert")
    workflow.add_edge("algo_expert", END)
    return workflow.compile()

# Compile the graph once when the server starts
interview_app = build_interview_graph()

# 6. The function FastAPI calls
def get_ai_response(problem_data: dict, user_message: str) -> str:
    # Format the LeetCode problem cleanly
    context = (
        f"Title: {problem_data['title']}\n"
        f"Description: {problem_data['description']}\n"
        f"Constraints: {problem_data['constraints']}"
    )
    
    # Setup the initial state for this specific turn
    initial_state = {
        "problem_context": context,
        "messages": [HumanMessage(content=user_message)],
        "current_phase": "algorithm"
    }
    
    # Run the graph
    result = interview_app.invoke(initial_state)
    
    # Return the very last message generated by the AI
    return result["messages"][-1].content